package tips

import "github.com/Dxrk777/Dxrk-Ai/internal/strconst"

// DefaultTips returns the default set of tips for Dxrk-Ai.
func DefaultTips() []Tip {
	return []Tip{
		{
			ID:        "getting-started",
			Category:  "getting-started",
			Title:     "Welcome to Dxrk-Ai",
			Content:   "Dxrk-Ai is a powerful AI coding assistant. Use /help to see all available commands.",
			Trigger:   TriggerOnStart,
			Frequency: FrequencyOnce,
			Priority:  100,
			Enabled:   true,
		},
		{
			ID:        "file-tools",
			Category:  "tools",
			Title:     "File Operations",
			Content:   "Use file_read, file_write, and file_edit tools to interact with files in your project.",
			Trigger:   TriggerOnStart,
			Frequency: FrequencyWeekly,
			Priority:  90,
			Enabled:   true,
		},
		{
			ID:        "shell-tool",
			Category:  "tools",
			Title:     "Shell Commands",
			Content:   "Run shell commands safely with the shell tool. Dangerous commands are validated before execution.",
			Trigger:   TriggerOnToolUse,
			Frequency: FrequencyWeekly,
			Priority:  85,
			Enabled:   true,
		},
		{
			ID:        "compact-hint",
			Category:  strconst.StrEfficiency,
			Title:     "Conversation Compaction",
			Content:   "Long conversations are automatically compacted to save tokens. You can also use /compact manually.",
			Trigger:   TriggerOnTask,
			Frequency: FrequencyDaily,
			Priority:  70,
			Enabled:   true,
		},
		{
			ID:        "context-budget",
			Category:  strconst.StrEfficiency,
			Title:     "Context Budget",
			Content:   "Monitor your context usage with the status bar. When usage is high, older messages are compacted.",
			Trigger:   TriggerOnIdle,
			Frequency: FrequencyDaily,
			Priority:  60,
			Enabled:   true,
		},
		{
			ID:        "error-recovery",
			Category:  "reliability",
			Title:     "Error Recovery",
			Content:   "If a tool fails, try again or use a different approach. The agent will adapt to find a solution.",
			Trigger:   TriggerOnError,
			Frequency: FrequencyAlways,
			Priority:  80,
			Enabled:   true,
		},
		{
			ID:        "permissions",
			Category:  "security",
			Title:     "Tool Permissions",
			Content:   "Review tool permissions before allowing potentially destructive operations. Use 'yolo' mode carefully.",
			Trigger:   TriggerOnFirstUse,
			Frequency: FrequencyOnce,
			Priority:  75,
			Enabled:   true,
		},
		{
			ID:        "parallel-tasks",
			Category:  strconst.StrEfficiency,
			Title:     "Parallel Execution",
			Content:   "The agent can run multiple tools in parallel for faster results.",
			Trigger:   TriggerOnTask,
			Frequency: FrequencyWeekly,
			Priority:  65,
			Enabled:   true,
		},
		{
			ID:        "memory-system",
			Category:  "features",
			Title:     "Memory System",
			Content:   "Dxrk-Ai remembers context across sessions. Important decisions are saved automatically.",
			Trigger:   TriggerOnStart,
			Frequency: FrequencyWeekly,
			Priority:  55,
			Enabled:   true,
		},
		{
			ID:        "skills",
			Category:  "features",
			Title:     "Skills",
			Content:   "Extend functionality with skills. Use /skills to see available options.",
			Trigger:   TriggerOnIdle,
			Frequency: FrequencyWeekly,
			Priority:  50,
			Enabled:   true,
		},
	}
}
