// SPDX-License-Identifier: MIT
package memory

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// ConsolidationConfig controls memory consolidation behavior.
type ConsolidationConfig struct {
	// MaxMemoryFiles caps how many .md files a memory dir can hold.
	MaxMemoryFiles int
	// MaxMemoryLines caps lines per MEMORY.md entrypoint.
	MaxMemoryLines int
	// MaxMemoryBytes caps MEMORY.md file size in bytes.
	MaxMemoryBytes int
	// StaleThresholdDays marks memories older than this as stale.
	StaleThresholdDays int
	// AutoConsolidate enables automatic daily consolidation.
	AutoConsolidate bool
	// ConsolidationInterval is how often to run consolidation.
	ConsolidationInterval time.Duration
}

// DefaultConsolidationConfig returns sensible defaults.
func DefaultConsolidationConfig() ConsolidationConfig {
	return ConsolidationConfig{
		MaxMemoryFiles:        200,
		MaxMemoryLines:        200,
		MaxMemoryBytes:        25 * 1024, // 25KB
		StaleThresholdDays:    7,
		AutoConsolidate:       true,
		ConsolidationInterval: 24 * time.Hour,
	}
}

// ConsolidationResult describes the outcome of a consolidation pass.
type ConsolidationResult struct {
	FilesScanned      int
	FilesConsolidated int
	FilesPruned       int
	MEMORYUpdated     bool
	PrunedFiles       []string
	Errors            []error
}

// Consolidator manages memory consolidation (auto-dream, compaction).
type Consolidator struct {
	config  ConsolidationConfig
	rootDir string
}

// NewConsolidator creates a new consolidator.
func NewConsolidator(rootDir string, config ConsolidationConfig) *Consolidator {
	return &Consolidator{
		config:  config,
		rootDir: rootDir,
	}
}

// Consolidate runs a full consolidation pass:
// 1. Scan all memory files
// 2. Prune stale/empty files
// 3. Update MEMORY.md entrypoint with consolidated summary
func (c *Consolidator) Consolidate() (*ConsolidationResult, error) {
	result := &ConsolidationResult{}

	memoryDir := filepath.Join(c.rootDir, ".memories")
	if err := os.MkdirAll(memoryDir, 0o750); err != nil {
		return nil, fmt.Errorf("create memory dir: %w", err)
	}

	// Step 1: Scan.
	headers, err := ScanMemoryFiles(memoryDir)
	if err != nil {
		return nil, err
	}
	result.FilesScanned = len(headers)

	// Step 2: Prune stale files.
	for _, h := range headers {
		ageDays := MemoryAgeDays(h.MtimeMs)
		if ageDays > c.config.StaleThresholdDays {
			if err := os.Remove(h.FilePath); err == nil {
				result.FilesPruned++
				result.PrunedFiles = append(result.PrunedFiles, h.Filename)
			}
		}
	}

	// Step 3: Re-scan after pruning.
	headers, err = ScanMemoryFiles(memoryDir)
	if err != nil {
		return nil, err
	}

	// Step 4: Enforce max files (keep newest).
	if len(headers) > c.config.MaxMemoryFiles {
		toRemove := headers[c.config.MaxMemoryFiles:]
		for _, h := range toRemove {
			if err := os.Remove(h.FilePath); err == nil {
				result.FilesPruned++
				result.PrunedFiles = append(result.PrunedFiles, h.Filename)
			}
		}
		headers = headers[:c.config.MaxMemoryFiles]
	}

	// Step 5: Update MEMORY.md entrypoint.
	entrypoint := filepath.Join(memoryDir, entrypointName)
	content := c.renderEntrypoint(headers)

	if len(content) > c.config.MaxMemoryBytes {
		content = content[:c.config.MaxMemoryBytes]
		// Find last complete line.
		if idx := strings.LastIndex(content, "\n"); idx > 0 {
			content = content[:idx+1]
		}
	}

	if err := os.WriteFile(entrypoint, []byte(content), 0o600); err != nil {
		result.Errors = append(result.Errors, fmt.Errorf("write MEMORY.md: %w", err))
	} else {
		result.MEMORYUpdated = true
	}

	result.FilesConsolidated = len(headers)
	return result, nil
}

// renderEntrypoint renders the MEMORY.md entrypoint file.
func (c *Consolidator) renderEntrypoint(headers []MemoryHeader) string {
	var lines []string
	lines = append(lines, "# Memory Index", "")
	lines = append(lines, "<!-- Auto-generated by memory consolidation. Do not edit manually. -->", "")
	lines = append(lines, fmt.Sprintf("Last updated: %s", time.Now().UTC().Format("2006-01-02 15:04:05 UTC")), "")
	lines = append(lines, "")

	// Group by type.
	byType := make(map[MemType][]MemoryHeader)
	for _, h := range headers {
		t := h.Type
		if t == "" {
			t = "reference"
		}
		byType[t] = append(byType[t], h)
	}

	typeOrder := []MemType{MemTypeUser, MemTypeFeedback, MemTypeProject, MemTypeReference}
	typeLabels := map[MemType]string{
		MemTypeUser:      "User Preferences",
		MemTypeFeedback:  "Feedback & Corrections",
		MemTypeProject:   "Project Knowledge",
		MemTypeReference: "Reference Material",
	}

	for _, t := range typeOrder {
		memories := byType[t]
		if len(memories) == 0 {
			continue
		}
		lines = append(lines, fmt.Sprintf("## %s", typeLabels[t]), "")
		for _, m := range memories {
			age := MemoryAge(m.MtimeMs)
			ageStr := fmt.Sprintf(" (%s)", age)
			if m.Description != "" {
				lines = append(lines, fmt.Sprintf("- `%s`%s — %s", m.Filename, ageStr, m.Description))
			} else {
				lines = append(lines, fmt.Sprintf("- `%s`%s", m.Filename, ageStr))
			}
		}
		lines = append(lines, "")
	}

	return strings.Join(lines, "\n")
}

// CompactMemories merges related memories into fewer, denser files.
func (c *Consolidator) CompactMemories(memoryDir string) (int, error) {
	headers, err := ScanMemoryFiles(memoryDir)
	if err != nil {
		return 0, err
	}

	// Group by type for compaction.
	byType := make(map[MemType][]MemoryHeader)
	for _, h := range headers {
		t := h.Type
		if t == "" {
			t = MemTypeReference
		}
		byType[t] = append(byType[t], h)
	}

	compacted := 0
	for t, memories := range byType {
		if len(memories) <= 3 {
			continue // Not enough to compact.
		}

		// Sort by mtime ascending (oldest first).
		sort.Slice(memories, func(i, j int) bool {
			return memories[i].MtimeMs < memories[j].MtimeMs
		})

		// Merge oldest half into a single consolidated file.
		mergeCount := len(memories) / 2
		var mergedContent strings.Builder
		fmt.Fprintf(&mergedContent, "---\nname: consolidated-%s\n", t)
		fmt.Fprintf(&mergedContent, "description: Auto-consolidated from %d files\n", mergeCount)
		fmt.Fprintf(&mergedContent, "type: %s\n---\n\n", t)

		for i := 0; i < mergeCount; i++ {
			data, err := os.ReadFile(memories[i].FilePath) //nolint:gosec
			if err != nil {
				continue
			}
			_, _, body := ParseFrontmatter(string(data))
			mergedContent.WriteString(body)
			mergedContent.WriteString("\n\n")
			os.Remove(memories[i].FilePath) //nolint:errcheck
			compacted++
		}

		// Write the consolidated file.
		outPath := filepath.Join(memoryDir, fmt.Sprintf("consolidated-%s.md", t))
		os.WriteFile(outPath, []byte(mergedContent.String()), 0o600) //nolint:errcheck
	}

	return compacted, nil
}

// PruneStale removes memory files older than the stale threshold.
func (c *Consolidator) PruneStale(memoryDir string) (int, error) {
	headers, err := ScanMemoryFiles(memoryDir)
	if err != nil {
		return 0, err
	}

	pruned := 0
	for _, h := range headers {
		ageDays := MemoryAgeDays(h.MtimeMs)
		if ageDays > c.config.StaleThresholdDays {
			if err := os.Remove(h.FilePath); err == nil {
				pruned++
			}
		}
	}
	return pruned, nil
}

// WriteMemoryFile creates a new memory file with frontmatter.
func WriteMemoryFile(memoryDir, name, description string, memType MemType, content string) error {
	if err := os.MkdirAll(memoryDir, 0o750); err != nil {
		return fmt.Errorf("create memory dir: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("---\n")
	fmt.Fprintf(&sb, "name: %s\n", name)
	if description != "" {
		fmt.Fprintf(&sb, "description: %s\n", description)
	}
	if memType != "" {
		fmt.Fprintf(&sb, "type: %s\n", memType)
	}
	sb.WriteString("---\n\n")
	sb.WriteString(content)

	filePath := filepath.Join(memoryDir, name+".md")
	return os.WriteFile(filePath, []byte(sb.String()), 0o600)
}
