run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - testdata
    - e2e
    - docs
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
        - dupl
        - goconst
    - path: e2e/
      linters:
        - gosec
        - gocyclo
  max-issues-per-linter: 100
  max-same-issues: 20

linters:
  enable:
    - gofmt
    - gosec
    - nakedret

linters-settings:
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G104
  nakedret:
    max-func-lines: 30

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true
