# SPDX-License-Identifier: MIT
"""GGA component — ports internal/components/gga/.

Config, install, runtime file management.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

from dxrk.components import filemerge
from dxrk.components.assets import read as assets_read
from dxrk.models import AgentID
from dxrk.system import PlatformProfile


@dataclass
class InjectionResult:
    ConfigFile: str = ""
    AgentsFile: str = ""
    ConfigChanged: bool = False
    AgentsChanged: bool = False

    def files_written(self) -> list[str]:
        files: list[str] = []
        if self.ConfigFile:
            files.append(self.ConfigFile)
        if self.AgentsFile:
            files.append(self.AgentsFile)
        return files


def post_install_messages() -> list[str]:
    return [
        "Run `DXRK_GUARDIAN install` in any git project to set up the pre-commit hook",
        "Copy `~/.config/DXRK_GUARDIAN/AGENTS.md` to your project root and customize it",
    ]


def provider_for_agents(agent_ids: list[AgentID]) -> str:
    has = set(agent_ids)
    if AgentID.CLAUDE_CODE in has:
        return "claude"
    if AgentID.OPENCODE in has:
        return "opencode"
    if AgentID.GEMINI_CLI in has:
        return "gemini"
    if AgentID.ANTIGRAVITY in has:
        return "gemini"
    if AgentID.CODEX in has:
        return "codex"
    return "claude"


def build_config(provider: str) -> bytes:
    lines = [
        "# Dxrk Guardian Angel Configuration",
        "# Generated by dxrk",
        "",
        "# AI Provider for code review",
        "# Options: claude, gemini, codex, opencode, ollama:<model>",
        f"PROVIDER={provider!r}",
        "",
        "# File patterns to review (comma-separated globs)",
        'FILE_PATTERNS="*.ts,*.tsx,*.js,*.jsx,*.py,*.go"',
        "",
        "# Patterns to exclude",
        'EXCLUDE_PATTERNS="*.test.*,*.spec.*,*.d.ts,dist/*,build/*,node_modules/*"',
        "",
        "# Rules file",
        'RULES_FILE="AGENTS.md"',
        "",
        "# Strict mode (fail on ambiguous AI responses)",
        'STRICT_MODE="true"',
        "",
        "# Review timeout in seconds",
        'TIMEOUT="300"',
        "",
    ]
    return ("\n".join(lines)).encode("utf-8")


def config_path(home_dir: str) -> str:
    return os.path.join(home_dir, ".config", "DXRK_GUARDIAN", "config")


def agents_template_path(home_dir: str) -> str:
    return os.path.join(home_dir, ".config", "DXRK_GUARDIAN", "AGENTS.md")


def inject(home_dir: str, agent_ids: list[AgentID]) -> InjectionResult:
    provider = provider_for_agents(agent_ids)
    config_content = build_config(provider)
    cpath = config_path(home_dir)
    config_result = filemerge.write_file_atomic(cpath, config_content, 0o644)

    agents_content = assets_read("gga/AGENTS.md") or ""
    apath = agents_template_path(home_dir)
    agents_result = filemerge.write_file_atomic(
        apath, agents_content.encode("utf-8"), 0o644
    )

    return InjectionResult(
        ConfigFile=cpath,
        AgentsFile=apath,
        ConfigChanged=config_result.Changed,
        AgentsChanged=agents_result.Changed,
    )


def install_command(profile: PlatformProfile) -> list[list[str]]:
    from dxrk.models import ComponentID
    from dxrk.pipeline import resolve_component_install

    return resolve_component_install(profile, ComponentID.DXRK_GUARDIAN)


def should_install(enabled: bool) -> bool:
    return enabled


# ─── Runtime ───────────────────────────────────────────────────────────────


def runtime_lib_dir(home_dir: str) -> str:
    return os.path.join(home_dir, ".local", "share", "DXRK_GUARDIAN", "lib")


def runtime_bin_dir(home_dir: str) -> str:
    return os.path.join(home_dir, ".local", "share", "DXRK_GUARDIAN", "bin")


def runtime_pr_mode_path(home_dir: str) -> str:
    return os.path.join(runtime_lib_dir(home_dir), "pr_mode.sh")


def runtime_ps1_path(home_dir: str) -> str:
    return os.path.join(home_dir, "bin", "DXRK_GUARDIAN.ps1")


def ensure_runtime_assets(home_dir: str) -> None:
    pr_mode_path = runtime_pr_mode_path(home_dir)
    content = assets_read("gga/pr_mode.sh")
    if content is None:
        raise FileNotFoundError("embedded gga runtime asset pr_mode.sh not found")
    filemerge.write_file_atomic(pr_mode_path, content.encode("utf-8"), 0o755)


def ensure_powershell_shim(home_dir: str) -> None:
    ps1_path = runtime_ps1_path(home_dir)
    content = assets_read("gga/gga.ps1")
    if content is None:
        raise FileNotFoundError("embedded gga runtime asset gga.ps1 not found")
    filemerge.write_file_atomic(ps1_path, content.encode("utf-8"), 0o755)
