// SPDX-License-Identifier: MIT
package catalog

import "github.com/Dxrk777/Dxrk-Ai/internal/model"

const catWorkflow = "workflow"

type Skill struct {
	ID       model.SkillID
	Name     string
	Category string
	Priority string
}

var mvpSkills = []Skill{
	// ── SDD skills ─────────────────────────────────────────────────
	{ID: model.SkillSDDInit, Name: "sdd-init", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDApply, Name: "sdd-apply", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDVerify, Name: "sdd-verify", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDExplore, Name: "sdd-explore", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDPropose, Name: "sdd-propose", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDSpec, Name: "sdd-spec", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDDesign, Name: "sdd-design", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDTasks, Name: "sdd-tasks", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDArchive, Name: "sdd-archive", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDOnboard, Name: "sdd-onboard", Category: "sdd", Priority: "p0"},
	// ── Foundation / Workflow ──────────────────────────────────────
	{ID: model.SkillGoTesting, Name: "go-testing", Category: "testing", Priority: "p0"},
	{ID: model.SkillCreator, Name: "skill-creator", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillJudgmentDay, Name: "judgment-day", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillBranchPR, Name: "branch-pr", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillIssueCreation, Name: "issue-creation", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillSkillRegistry, Name: "skill-registry", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillChainedPR, Name: "chained-pr", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillCognitiveDoc, Name: "cognitive-doc-design", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillCommentWriter, Name: "comment-writer", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillWorkUnitCommits, Name: "work-unit-commits", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillLLMCouncil, Name: "llm-council", Category: "analysis", Priority: "p0"},
	// ── Programming Languages ─────────────────────────────────────
	{ID: model.SkillPythonPro, Name: "python-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillPythonPatterns, Name: "python-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillAsyncPythonPatterns, Name: "async-python-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillPythonFastapi, Name: "python-fastapi-development", Category: "language", Priority: "p1"},
	{ID: model.SkillPythonPackaging, Name: "python-packaging", Category: "language", Priority: "p2"},
	{ID: model.SkillPythonPerformance, Name: "python-performance-optimization", Category: "language", Priority: "p2"},
	{ID: model.SkillPytestSkill, Name: "pytest-skill", Category: "testing", Priority: "p1"},
	{ID: model.SkillPydanticAI, Name: "pydantic-ai", Category: "language", Priority: "p1"},
	{ID: model.SkillJavaScriptPro, Name: "javascript-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillJavaScriptMastery, Name: "javascript-mastery", Category: "language", Priority: "p1"},
	{ID: model.SkillJavaScriptDesign, Name: "javascript-design-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillNodejsPro, Name: "nodejs-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillTypeScriptPro, Name: "typescript-pro", Category: "language", Priority: "p0"},
	{ID: model.SkillNextjsPro, Name: "nextjs-pro", Category: "web", Priority: "p1"},
	{ID: model.SkillRustPro, Name: "rust-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillRustAsync, Name: "rust-async-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillMemorySafetyPatterns, Name: "memory-safety-patterns", Category: "language", Priority: "p2"},
	{ID: model.SkillGolangPro, Name: "golang-pro", Category: "language", Priority: "p0"},
	{ID: model.SkillGoConcurrencyPatterns, Name: "go-concurrency-patterns", Category: "language", Priority: "p0"},
	{ID: model.SkillGoInDepth, Name: "go-in-depth", Category: "language", Priority: "p1"},
	{ID: model.SkillGoPlaywright, Name: "go-playwright", Category: "language", Priority: "p2"},
	{ID: model.SkillGoRodMaster, Name: "go-rod-master", Category: "language", Priority: "p2"},
	{ID: model.SkillGrpcGolang, Name: "grpc-golang", Category: "language", Priority: "p2"},
	{ID: model.SkillTemporalGolangPro, Name: "temporal-golang-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillJavaPro, Name: "java-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillSpringbootPro, Name: "springboot-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillJavaPerformanceTuning, Name: "java-performance-tuning", Category: "language", Priority: "p2"},
	{ID: model.SkillCppPro, Name: "cpp-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillCppLowLatency, Name: "cpp-low-latency", Category: "language", Priority: "p2"},
	{ID: model.SkillSwiftPro, Name: "swift-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillSwiftConcurrency, Name: "swift-concurrency-expert", Category: "language", Priority: "p2"},
	{ID: model.SkillSwiftuiExpert, Name: "swiftui-expert", Category: "language", Priority: "p2"},
	{ID: model.SkillKotlinPro, Name: "kotlin-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillKotlinMultiplatform, Name: "kotlin-multiplatform", Category: "language", Priority: "p2"},
	{ID: model.SkillAndroidCompose, Name: "android-jetpack-compose-expert", Category: "mobile", Priority: "p2"},
	{ID: model.SkillRubyRailsPro, Name: "ruby-rails-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillPhpPro, Name: "php-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillPhpLaravelPro, Name: "php-laravel-pro", Category: "language", Priority: "p2"},
	// ── Web / Frontend ────────────────────────────────────────────
	{ID: model.SkillReactBestPractices, Name: "react-best-practices", Category: "web", Priority: "p1"},
	{ID: model.SkillReactPatterns, Name: "react-patterns", Category: "web", Priority: "p1"},
	{ID: model.SkillAngularPro, Name: "angular-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillSveltePro, Name: "svelte-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillVuePro, Name: "vue-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillTailwindPro, Name: "tailwind-pro", Category: "web", Priority: "p1"},
	{ID: model.SkillCssPro, Name: "css-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillHtmlPro, Name: "html-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillFrontendArch, Name: "frontend-architecture", Category: "web", Priority: "p1"},
	{ID: model.SkillReactCompPerf, Name: "react-component-performance", Category: "web", Priority: "p2"},
	// ── DevOps / Cloud ────────────────────────────────────────────
	{ID: model.SkillDockerExpert, Name: "docker-expert", Category: "devops", Priority: "p0"},
	{ID: model.SkillKubernetesArchitect, Name: "kubernetes-architect", Category: "devops", Priority: "p0"},
	{ID: model.SkillTerraformPatterns, Name: "terraform-patterns", Category: "devops", Priority: "p1"},
	{ID: model.SkillAWSArchitect, Name: "aws-architect", Category: "devops", Priority: "p1"},
	{ID: model.SkillCloudArchitect, Name: "cloud-architect", Category: "devops", Priority: "p1"},
	{ID: model.SkillGitHubActionsAdvanced, Name: "github-actions-advanced", Category: "devops", Priority: "p1"},
	{ID: model.SkillCICDPipelineBuilder, Name: "ci-cd-pipeline-builder", Category: "devops", Priority: "p1"},
	{ID: model.SkillGitopsWorkflow, Name: "gitops-workflow", Category: "devops", Priority: "p2"},
	{ID: model.SkillArgoCDPro, Name: "argocd-pro", Category: "devops", Priority: "p2"},
	{ID: model.SkillHelmChartBuilder, Name: "helm-chart-builder", Category: "devops", Priority: "p2"},
	{ID: model.SkillAWSLambdaPro, Name: "aws-lambda-pro", Category: "devops", Priority: "p2"},
	// ── AI / ML ───────────────────────────────────────────────────
	{ID: model.SkillPromptEngineering, Name: "prompt-engineering-patterns", Category: "ai", Priority: "p0"},
	{ID: model.SkillAgentDesigner, Name: "agent-designer", Category: "ai", Priority: "p0"},
	{ID: model.SkillMemorySystems, Name: "memory-systems", Category: "ai", Priority: "p1"},
	{ID: model.SkillLLMAppPatterns, Name: "llm-app-patterns", Category: "ai", Priority: "p1"},
	{ID: model.SkillLLMEvaluation, Name: "llm-evaluation", Category: "ai", Priority: "p1"},
	{ID: model.SkillRAGArchitect, Name: "rag-architect", Category: "ai", Priority: "p1"},
	{ID: model.SkillRAGEngineer, Name: "rag-engineer", Category: "ai", Priority: "p1"},
	{ID: model.SkillAIEngineeringToolkit, Name: "ai-engineering-toolkit", Category: "ai", Priority: "p1"},
	{ID: model.SkillFineTuningPro, Name: "fine-tuning-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillLangChainPro, Name: "langchain-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillEmbeddingPro, Name: "embedding-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillVectorDBPro, Name: "vector-db-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillMLOpsPro, Name: "ml-ops-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillComputerVisionPro, Name: "computer-vision-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillNLPPro, Name: "nlp-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillHuggingFaceCLI, Name: "hugging-face-cli", Category: "ai", Priority: "p2"},
	{ID: model.SkillLangGraph, Name: "langgraph", Category: "ai", Priority: "p2"},
	// ── Data ──────────────────────────────────────────────────────
	{ID: model.SkillDataEngineer, Name: "data-engineer", Category: "data", Priority: "p1"},
	{ID: model.SkillDataPipeline, Name: "data-engineering-data-pipeline", Category: "data", Priority: "p1"},
	{ID: model.SkillPostgresBestPractices, Name: "postgres-best-practices", Category: "data", Priority: "p1"},
	{ID: model.SkillRedisPro, Name: "redis-pro", Category: "data", Priority: "p2"},
	{ID: model.SkillMongoDBPro, Name: "mongodb-pro", Category: "data", Priority: "p2"},
	{ID: model.SkillDataVisualization, Name: "data-visualization", Category: "data", Priority: "p2"},
	{ID: model.SkillDBQuery, Name: "db-query", Category: "data", Priority: "p1"},
	{ID: model.SkillMigration, Name: "migration", Category: "data", Priority: "p1"},
	// ── Mobile ────────────────────────────────────────────────────
	{ID: model.SkillReactNative, Name: "react-native", Category: "mobile", Priority: "p2"},
	{ID: model.SkillAndroidDev, Name: "android-dev", Category: "mobile", Priority: "p2"},
	{ID: model.SkillFlutterPro, Name: "flutter-pro", Category: "mobile", Priority: "p2"},
	{ID: model.SkillIOSPro, Name: "ios-pro", Category: "mobile", Priority: "p2"},
	{ID: model.SkillMobileTesting, Name: "mobile-app-testing", Category: "testing", Priority: "p2"},
	// ── Security ──────────────────────────────────────────────────
	{ID: model.SkillSecuritySAST, Name: "security-scanning-security-sast", Category: "security", Priority: "p1"},
	{ID: model.SkillSecurityHardening, Name: "security-scanning-security-hardening", Category: "security", Priority: "p1"},
	{ID: model.SkillSecurityDependencies, Name: "security-scanning-security-dependencies", Category: "security", Priority: "p1"},
	{ID: model.SkillAPISecurity, Name: "api-security-best-practices", Category: "security", Priority: "p1"},
	{ID: model.SkillContainerSecurity, Name: "container-security-hardening", Category: "security", Priority: "p2"},
	{ID: model.SkillCloudSecurity, Name: "cloud-security", Category: "security", Priority: "p2"},
	{ID: model.SkillPenetrationTesting, Name: "penetration-testing", Category: "security", Priority: "p2"},
	// ── Testing ───────────────────────────────────────────────────
	{ID: model.SkillTDDGuide, Name: "tdd-guide", Category: "testing", Priority: "p1"},
	{ID: model.SkillE2ETesting, Name: "e2e-testing", Category: "testing", Priority: "p1"},
	{ID: model.SkillK6LoadTesting, Name: "k6-load-testing", Category: "testing", Priority: "p2"},
	{ID: model.SkillTestingPatterns, Name: "testing-patterns", Category: "testing", Priority: "p1"},
	{ID: model.SkillTestAutomator, Name: "test-automator", Category: "testing", Priority: "p2"},
	{ID: model.SkillPlaywrightPro, Name: "playwright-pro", Category: "testing", Priority: "p1"},
	{ID: model.SkillCypressPro, Name: "cypress-pro", Category: "testing", Priority: "p2"},
	// ── Architecture ──────────────────────────────────────────────
	{ID: model.SkillSoftwareArchitecture, Name: "software-architecture", Category: "architecture", Priority: "p1"},
	{ID: model.SkillMicroservicesPatterns, Name: "microservices-patterns", Category: "architecture", Priority: "p1"},
	{ID: model.SkillEventSourcingArchitect, Name: "event-sourcing-architect", Category: "architecture", Priority: "p2"},
	{ID: model.SkillDDDPro, Name: "ddd-pro", Category: "architecture", Priority: "p2"},
	{ID: model.SkillSagaOrchestration, Name: "saga-orchestration", Category: "architecture", Priority: "p2"},
	// ── CLI / Terminal ────────────────────────────────────────────
	{ID: model.SkillBashPro, Name: "bash-pro", Category: "cli", Priority: "p1"},
	{ID: model.SkillBashScripting, Name: "bash-scripting", Category: "cli", Priority: "p1"},
	{ID: model.SkillPosixShellPro, Name: "posix-shell-pro", Category: "cli", Priority: "p2"},
	{ID: model.SkillAiNativeCLI, Name: "ai-native-cli", Category: "cli", Priority: "p2"},
	{ID: model.SkillJq, Name: "jq", Category: "cli", Priority: "p2"},
	// ── Documentation ─────────────────────────────────────────────
	{ID: model.SkillAPIDocs, Name: "api-docs", Category: "documentation", Priority: "p1"},
	{ID: model.SkillDocGeneration, Name: "documentation-generation", Category: "documentation", Priority: "p1"},
	{ID: model.SkillChangelogPro, Name: "changelog-pro", Category: "documentation", Priority: "p2"},
	{ID: model.SkillReadmePro, Name: "readme-pro", Category: "documentation", Priority: "p2"},
	// ── Images / Media ────────────────────────────────────────────
	{ID: model.SkillImageGeneration, Name: "image-generation", Category: "media", Priority: "p1"},
	{ID: model.SkillVideoEditing, Name: "video-editing", Category: "media", Priority: "p2"},
	{ID: model.SkillAudioProcessing, Name: "audio-processing", Category: "media", Priority: "p2"},
	{ID: model.Skill3DModeling, Name: "3d-modeling", Category: "media", Priority: "p2"},
	{ID: model.SkillAlgorithmicArt, Name: "algorithmic-art", Category: "media", Priority: "p2"},
	// ── PDF / Documents ───────────────────────────────────────────
	{ID: model.SkillPDFGeneration, Name: "pdf-generation", Category: "documents", Priority: "p1"},
	{ID: model.SkillWordDocx, Name: "word-docx", Category: "documents", Priority: "p1"},
	{ID: model.SkillExcelXlsx, Name: "excel-xlsx", Category: "documents", Priority: "p1"},
	{ID: model.SkillPPTXDeck, Name: "pptx-deck-creation", Category: "documents", Priority: "p2"},
	// ── Business ──────────────────────────────────────────────────
	{ID: model.SkillProductManagement, Name: "product-management", Category: "business", Priority: "p2"},
	{ID: model.SkillAgileScrum, Name: "agile-scrum", Category: "business", Priority: "p2"},
	{ID: model.SkillOKRTracking, Name: "okr-tracking", Category: "business", Priority: "p2"},
	// ── Writing ───────────────────────────────────────────────────
	{ID: model.SkillTechnicalWriting, Name: "technical-writing", Category: "writing", Priority: "p1"},
	{ID: model.SkillCopywriting, Name: "copywriting", Category: "writing", Priority: "p2"},
	{ID: model.SkillSEOWriting, Name: "seo-writing", Category: "writing", Priority: "p2"},
	{ID: model.SkillBlogWriting, Name: "blog-writing", Category: "writing", Priority: "p2"},
	// ── Code Quality ──────────────────────────────────────────────
	{ID: model.SkillCodeReviewChecklist, Name: "code-review-checklist", Category: "quality", Priority: "p1"},
	{ID: model.SkillRefactoringPatterns, Name: "refactoring-patterns", Category: "quality", Priority: "p1"},
	{ID: model.SkillErrorHandlingPatterns, Name: "error-handling-patterns", Category: "quality", Priority: "p1"},
	{ID: model.SkillSystematicDebugging, Name: "systematic-debugging", Category: "quality", Priority: "p1"},
	{ID: model.SkillCodeSimplification, Name: "code-simplification", Category: "quality", Priority: "p2"},
	// ── Observability ─────────────────────────────────────────────
	{ID: model.SkillObservability, Name: "observability-and-instrumentation", Category: "observability", Priority: "p2"},
	{ID: model.SkillIncidentResponder, Name: "incident-responder", Category: "observability", Priority: "p2"},
	{ID: model.SkillPostmortem, Name: "postmortem", Category: "observability", Priority: "p2"},
	{ID: model.SkillChaosEngineering, Name: "chaos-engineering", Category: "observability", Priority: "p2"},
	// ── Opencode extras ───────────────────────────────────────────
	{ID: model.SkillAccessiblity, Name: "accessibility", Category: "web", Priority: "p1"},
	{ID: model.SkillArchDecision, Name: "arch-decision", Category: "architecture", Priority: "p1"},
	{ID: model.SkillCICD, Name: "ci-cd", Category: "devops", Priority: "p1"},
	{ID: model.SkillCodeReview, Name: "code-review", Category: "quality", Priority: "p0"},
	{ID: model.SkillCommitMessage, Name: "commit-message", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillDebugging, Name: "debugging", Category: "quality", Priority: "p1"},
	{ID: model.SkillDependency, Name: "dependency", Category: "devops", Priority: "p1"},
	{ID: model.SkillDockerMgmt, Name: "docker-mgmt", Category: "devops", Priority: "p1"},
	{ID: model.SkillEnvSetup, Name: "env-setup", Category: "devops", Priority: "p1"},
	{ID: model.SkillErrorHandling, Name: "error-handling", Category: "quality", Priority: "p1"},
	{ID: model.SkillGitRelease, Name: "git-release", Category: catWorkflow, Priority: "p1"},
	{ID: model.SkillLoggingPatterns, Name: "logging-patterns", Category: "quality", Priority: "p1"},
	{ID: model.SkillPerformance, Name: "performance", Category: "quality", Priority: "p1"},
	{ID: model.SkillPRDescription, Name: "pr-description", Category: catWorkflow, Priority: "p1"},
	{ID: model.SkillRefactoringPR, Name: "refactoring-pr", Category: "quality", Priority: "p1"},
	{ID: model.SkillSecurityAudit, Name: "security-audit", Category: "security", Priority: "p1"},
	{ID: model.SkillTestWriter, Name: "test-writer", Category: "testing", Priority: "p1"},
}

func MVPSkills() []Skill {
	skills := make([]Skill, len(mvpSkills))
	copy(skills, mvpSkills)
	return skills
}
