// SPDX-License-Identifier: MIT
package catalog

import "github.com/Dxrk777/Dxrk-Ai/internal/model"

const catWorkflow = "workflow"

type Skill struct {
	ID       model.SkillID
	Name     string
	Category string
	Priority string
}

var mvpSkills = []Skill{
	// ── SDD skills ─────────────────────────────────────────────────
	{ID: model.SkillSDDInit, Name: "sdd-init", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDApply, Name: "sdd-apply", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDVerify, Name: "sdd-verify", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDExplore, Name: "sdd-explore", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDPropose, Name: "sdd-propose", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDSpec, Name: "sdd-spec", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDDesign, Name: "sdd-design", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDTasks, Name: "sdd-tasks", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDArchive, Name: "sdd-archive", Category: "sdd", Priority: "p0"},
	{ID: model.SkillSDDOnboard, Name: "sdd-onboard", Category: "sdd", Priority: "p0"},
	// ── Foundation / Workflow ──────────────────────────────────────
	{ID: model.SkillGoTesting, Name: "go-testing", Category: "testing", Priority: "p0"},
	{ID: model.SkillCreator, Name: "skill-creator", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillJudgmentDay, Name: "judgment-day", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillBranchPR, Name: "branch-pr", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillIssueCreation, Name: "issue-creation", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillSkillRegistry, Name: "skill-registry", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillChainedPR, Name: "chained-pr", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillCognitiveDoc, Name: "cognitive-doc-design", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillCommentWriter, Name: "comment-writer", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillWorkUnitCommits, Name: "work-unit-commits", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillLLMCouncil, Name: "llm-council", Category: "analysis", Priority: "p0"},
	// ── Programming Languages ─────────────────────────────────────
	{ID: model.SkillPythonPro, Name: "python-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillPythonPatterns, Name: "python-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillAsyncPythonPatterns, Name: "async-python-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillPythonFastapi, Name: "python-fastapi-development", Category: "language", Priority: "p1"},
	{ID: model.SkillPythonPackaging, Name: "python-packaging", Category: "language", Priority: "p2"},
	{ID: model.SkillPythonPerformance, Name: "python-performance-optimization", Category: "language", Priority: "p2"},
	{ID: model.SkillPytestSkill, Name: "pytest-skill", Category: "testing", Priority: "p1"},
	{ID: model.SkillPydanticAI, Name: "pydantic-ai", Category: "language", Priority: "p1"},
	{ID: model.SkillJavaScriptPro, Name: "javascript-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillJavaScriptMastery, Name: "javascript-mastery", Category: "language", Priority: "p1"},
	{ID: model.SkillJavaScriptDesign, Name: "javascript-design-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillNodejsPro, Name: "nodejs-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillTypeScriptPro, Name: "typescript-pro", Category: "language", Priority: "p0"},
	{ID: model.SkillNextjsPro, Name: "nextjs-pro", Category: "web", Priority: "p1"},
	{ID: model.SkillRustPro, Name: "rust-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillRustAsync, Name: "rust-async-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillMemorySafetyPatterns, Name: "memory-safety-patterns", Category: "language", Priority: "p2"},
	{ID: model.SkillGolangPro, Name: "golang-pro", Category: "language", Priority: "p0"},
	{ID: model.SkillGoConcurrencyPatterns, Name: "go-concurrency-patterns", Category: "language", Priority: "p0"},
	{ID: model.SkillGoInDepth, Name: "go-in-depth", Category: "language", Priority: "p1"},
	{ID: model.SkillGoPlaywright, Name: "go-playwright", Category: "language", Priority: "p2"},
	{ID: model.SkillGoRodMaster, Name: "go-rod-master", Category: "language", Priority: "p2"},
	{ID: model.SkillGrpcGolang, Name: "grpc-golang", Category: "language", Priority: "p2"},
	{ID: model.SkillTemporalGolangPro, Name: "temporal-golang-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillJavaPro, Name: "java-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillSpringbootPro, Name: "springboot-pro", Category: "language", Priority: "p1"},
	{ID: model.SkillJavaPerformanceTuning, Name: "java-performance-tuning", Category: "language", Priority: "p2"},
	{ID: model.SkillCppPro, Name: "cpp-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillCppLowLatency, Name: "cpp-low-latency", Category: "language", Priority: "p2"},
	{ID: model.SkillSwiftPro, Name: "swift-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillSwiftConcurrency, Name: "swift-concurrency-expert", Category: "language", Priority: "p2"},
	{ID: model.SkillSwiftuiExpert, Name: "swiftui-expert", Category: "language", Priority: "p2"},
	{ID: model.SkillKotlinPro, Name: "kotlin-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillKotlinMultiplatform, Name: "kotlin-multiplatform", Category: "language", Priority: "p2"},
	{ID: model.SkillAndroidCompose, Name: "android-jetpack-compose-expert", Category: "mobile", Priority: "p2"},
	{ID: model.SkillRubyRailsPro, Name: "ruby-rails-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillPhpPro, Name: "php-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillPhpLaravelPro, Name: "php-laravel-pro", Category: "language", Priority: "p2"},
	// ── Web / Frontend ────────────────────────────────────────────
	{ID: model.SkillReactBestPractices, Name: "react-best-practices", Category: "web", Priority: "p1"},
	{ID: model.SkillReactPatterns, Name: "react-patterns", Category: "web", Priority: "p1"},
	{ID: model.SkillAngularPro, Name: "angular-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillSveltePro, Name: "svelte-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillVuePro, Name: "vue-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillTailwindPro, Name: "tailwind-pro", Category: "web", Priority: "p1"},
	{ID: model.SkillCssPro, Name: "css-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillHtmlPro, Name: "html-pro", Category: "web", Priority: "p2"},
	{ID: model.SkillFrontendArch, Name: "frontend-architecture", Category: "web", Priority: "p1"},
	{ID: model.SkillReactCompPerf, Name: "react-component-performance", Category: "web", Priority: "p2"},
	// ── DevOps / Cloud ────────────────────────────────────────────
	{ID: model.SkillDockerExpert, Name: "docker-expert", Category: "devops", Priority: "p0"},
	{ID: model.SkillKubernetesArchitect, Name: "kubernetes-architect", Category: "devops", Priority: "p0"},
	{ID: model.SkillTerraformPatterns, Name: "terraform-patterns", Category: "devops", Priority: "p1"},
	{ID: model.SkillAWSArchitect, Name: "aws-architect", Category: "devops", Priority: "p1"},
	{ID: model.SkillCloudArchitect, Name: "cloud-architect", Category: "devops", Priority: "p1"},
	{ID: model.SkillGitHubActionsAdvanced, Name: "github-actions-advanced", Category: "devops", Priority: "p1"},
	{ID: model.SkillCICDPipelineBuilder, Name: "ci-cd-pipeline-builder", Category: "devops", Priority: "p1"},
	{ID: model.SkillGitopsWorkflow, Name: "gitops-workflow", Category: "devops", Priority: "p2"},
	{ID: model.SkillArgoCDPro, Name: "argocd-pro", Category: "devops", Priority: "p2"},
	{ID: model.SkillHelmChartBuilder, Name: "helm-chart-builder", Category: "devops", Priority: "p2"},
	{ID: model.SkillAWSLambdaPro, Name: "aws-lambda-pro", Category: "devops", Priority: "p2"},
	// ── AI / ML ───────────────────────────────────────────────────
	{ID: model.SkillPromptEngineering, Name: "prompt-engineering-patterns", Category: "ai", Priority: "p0"},
	{ID: model.SkillAgentDesigner, Name: "agent-designer", Category: "ai", Priority: "p0"},
	{ID: model.SkillMemorySystems, Name: "memory-systems", Category: "ai", Priority: "p1"},
	{ID: model.SkillLLMAppPatterns, Name: "llm-app-patterns", Category: "ai", Priority: "p1"},
	{ID: model.SkillLLMEvaluation, Name: "llm-evaluation", Category: "ai", Priority: "p1"},
	{ID: model.SkillRAGArchitect, Name: "rag-architect", Category: "ai", Priority: "p1"},
	{ID: model.SkillRAGEngineer, Name: "rag-engineer", Category: "ai", Priority: "p1"},
	{ID: model.SkillAIEngineeringToolkit, Name: "ai-engineering-toolkit", Category: "ai", Priority: "p1"},
	{ID: model.SkillFineTuningPro, Name: "fine-tuning-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillLangChainPro, Name: "langchain-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillEmbeddingPro, Name: "embedding-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillVectorDBPro, Name: "vector-db-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillMLOpsPro, Name: "ml-ops-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillComputerVisionPro, Name: "computer-vision-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillNLPPro, Name: "nlp-pro", Category: "ai", Priority: "p2"},
	{ID: model.SkillHuggingFaceCLI, Name: "hugging-face-cli", Category: "ai", Priority: "p2"},
	{ID: model.SkillLangGraph, Name: "langgraph", Category: "ai", Priority: "p2"},
	// ── Data ──────────────────────────────────────────────────────
	{ID: model.SkillDataEngineer, Name: "data-engineer", Category: "data", Priority: "p1"},
	{ID: model.SkillDataPipeline, Name: "data-engineering-data-pipeline", Category: "data", Priority: "p1"},
	{ID: model.SkillPostgresBestPractices, Name: "postgres-best-practices", Category: "data", Priority: "p1"},
	{ID: model.SkillRedisPro, Name: "redis-pro", Category: "data", Priority: "p2"},
	{ID: model.SkillMongoDBPro, Name: "mongodb-pro", Category: "data", Priority: "p2"},
	{ID: model.SkillDataVisualization, Name: "data-visualization", Category: "data", Priority: "p2"},
	{ID: model.SkillDBQuery, Name: "db-query", Category: "data", Priority: "p1"},
	{ID: model.SkillMigration, Name: "migration", Category: "data", Priority: "p1"},
	// ── Mobile ────────────────────────────────────────────────────
	{ID: model.SkillReactNative, Name: "react-native", Category: "mobile", Priority: "p2"},
	{ID: model.SkillAndroidDev, Name: "android-dev", Category: "mobile", Priority: "p2"},
	{ID: model.SkillFlutterPro, Name: "flutter-pro", Category: "mobile", Priority: "p2"},
	{ID: model.SkillIOSPro, Name: "ios-pro", Category: "mobile", Priority: "p2"},
	{ID: model.SkillMobileTesting, Name: "mobile-app-testing", Category: "testing", Priority: "p2"},
	// ── Security ──────────────────────────────────────────────────
	{ID: model.SkillSecuritySAST, Name: "security-scanning-security-sast", Category: "security", Priority: "p1"},
	{ID: model.SkillSecurityHardening, Name: "security-scanning-security-hardening", Category: "security", Priority: "p1"},
	{ID: model.SkillSecurityDependencies, Name: "security-scanning-security-dependencies", Category: "security", Priority: "p1"},
	{ID: model.SkillAPISecurity, Name: "api-security-best-practices", Category: "security", Priority: "p1"},
	{ID: model.SkillContainerSecurity, Name: "container-security-hardening", Category: "security", Priority: "p2"},
	{ID: model.SkillCloudSecurity, Name: "cloud-security", Category: "security", Priority: "p2"},
	{ID: model.SkillPenetrationTesting, Name: "penetration-testing", Category: "security", Priority: "p2"},
	// ── Testing ───────────────────────────────────────────────────
	{ID: model.SkillTDDGuide, Name: "tdd-guide", Category: "testing", Priority: "p1"},
	{ID: model.SkillE2ETesting, Name: "e2e-testing", Category: "testing", Priority: "p1"},
	{ID: model.SkillK6LoadTesting, Name: "k6-load-testing", Category: "testing", Priority: "p2"},
	{ID: model.SkillTestingPatterns, Name: "testing-patterns", Category: "testing", Priority: "p1"},
	{ID: model.SkillTestAutomator, Name: "test-automator", Category: "testing", Priority: "p2"},
	{ID: model.SkillPlaywrightPro, Name: "playwright-pro", Category: "testing", Priority: "p1"},
	{ID: model.SkillCypressPro, Name: "cypress-pro", Category: "testing", Priority: "p2"},
	// ── Architecture ──────────────────────────────────────────────
	{ID: model.SkillSoftwareArchitecture, Name: "software-architecture", Category: "architecture", Priority: "p1"},
	{ID: model.SkillMicroservicesPatterns, Name: "microservices-patterns", Category: "architecture", Priority: "p1"},
	{ID: model.SkillEventSourcingArchitect, Name: "event-sourcing-architect", Category: "architecture", Priority: "p2"},
	{ID: model.SkillDDDPro, Name: "ddd-pro", Category: "architecture", Priority: "p2"},
	{ID: model.SkillSagaOrchestration, Name: "saga-orchestration", Category: "architecture", Priority: "p2"},
	// ── CLI / Terminal ────────────────────────────────────────────
	{ID: model.SkillBashPro, Name: "bash-pro", Category: "cli", Priority: "p1"},
	{ID: model.SkillBashScripting, Name: "bash-scripting", Category: "cli", Priority: "p1"},
	{ID: model.SkillPosixShellPro, Name: "posix-shell-pro", Category: "cli", Priority: "p2"},
	{ID: model.SkillAiNativeCLI, Name: "ai-native-cli", Category: "cli", Priority: "p2"},
	{ID: model.SkillJq, Name: "jq", Category: "cli", Priority: "p2"},
	// ── Documentation ─────────────────────────────────────────────
	{ID: model.SkillAPIDocs, Name: "api-docs", Category: "documentation", Priority: "p1"},
	{ID: model.SkillDocGeneration, Name: "documentation-generation", Category: "documentation", Priority: "p1"},
	{ID: model.SkillChangelogPro, Name: "changelog-pro", Category: "documentation", Priority: "p2"},
	{ID: model.SkillReadmePro, Name: "readme-pro", Category: "documentation", Priority: "p2"},
	// ── Images / Media ────────────────────────────────────────────
	{ID: model.SkillImageGeneration, Name: "image-generation", Category: "media", Priority: "p1"},
	{ID: model.SkillVideoEditing, Name: "video-editing", Category: "media", Priority: "p2"},
	{ID: model.SkillAudioProcessing, Name: "audio-processing", Category: "media", Priority: "p2"},
	{ID: model.Skill3DModeling, Name: "3d-modeling", Category: "media", Priority: "p2"},
	{ID: model.SkillAlgorithmicArt, Name: "algorithmic-art", Category: "media", Priority: "p2"},
	// ── PDF / Documents ───────────────────────────────────────────
	{ID: model.SkillPDFGeneration, Name: "pdf-generation", Category: "documents", Priority: "p1"},
	{ID: model.SkillWordDocx, Name: "word-docx", Category: "documents", Priority: "p1"},
	{ID: model.SkillExcelXlsx, Name: "excel-xlsx", Category: "documents", Priority: "p1"},
	{ID: model.SkillPPTXDeck, Name: "pptx-deck-creation", Category: "documents", Priority: "p2"},
	// ── Business ──────────────────────────────────────────────────
	{ID: model.SkillProductManagement, Name: "product-management", Category: "business", Priority: "p2"},
	{ID: model.SkillAgileScrum, Name: "agile-scrum", Category: "business", Priority: "p2"},
	{ID: model.SkillOKRTracking, Name: "okr-tracking", Category: "business", Priority: "p2"},
	// ── Writing ───────────────────────────────────────────────────
	{ID: model.SkillTechnicalWriting, Name: "technical-writing", Category: "writing", Priority: "p1"},
	{ID: model.SkillCopywriting, Name: "copywriting", Category: "writing", Priority: "p2"},
	{ID: model.SkillSEOWriting, Name: "seo-writing", Category: "writing", Priority: "p2"},
	{ID: model.SkillBlogWriting, Name: "blog-writing", Category: "writing", Priority: "p2"},
	// ── Code Quality ──────────────────────────────────────────────
	{ID: model.SkillCodeReviewChecklist, Name: "code-review-checklist", Category: "quality", Priority: "p1"},
	{ID: model.SkillRefactoringPatterns, Name: "refactoring-patterns", Category: "quality", Priority: "p1"},
	{ID: model.SkillErrorHandlingPatterns, Name: "error-handling-patterns", Category: "quality", Priority: "p1"},
	{ID: model.SkillSystematicDebugging, Name: "systematic-debugging", Category: "quality", Priority: "p1"},
	{ID: model.SkillCodeSimplification, Name: "code-simplification", Category: "quality", Priority: "p2"},
	// ── Observability ─────────────────────────────────────────────
	{ID: model.SkillObservability, Name: "observability-and-instrumentation", Category: "observability", Priority: "p2"},
	{ID: model.SkillIncidentResponder, Name: "incident-responder", Category: "observability", Priority: "p2"},
	{ID: model.SkillPostmortem, Name: "postmortem", Category: "observability", Priority: "p2"},
	{ID: model.SkillChaosEngineering, Name: "chaos-engineering", Category: "observability", Priority: "p2"},
	// ── Opencode extras ───────────────────────────────────────────
	{ID: model.SkillAccessiblity, Name: "accessibility", Category: "web", Priority: "p1"},
	{ID: model.SkillArchDecision, Name: "arch-decision", Category: "architecture", Priority: "p1"},
	{ID: model.SkillCICD, Name: "ci-cd", Category: "devops", Priority: "p1"},
	{ID: model.SkillCodeReview, Name: "code-review", Category: "quality", Priority: "p0"},
	{ID: model.SkillCommitMessage, Name: "commit-message", Category: catWorkflow, Priority: "p0"},
	{ID: model.SkillDebugging, Name: "debugging", Category: "quality", Priority: "p1"},
	{ID: model.SkillDependency, Name: "dependency", Category: "devops", Priority: "p1"},
	{ID: model.SkillDockerMgmt, Name: "docker-mgmt", Category: "devops", Priority: "p1"},
	{ID: model.SkillEnvSetup, Name: "env-setup", Category: "devops", Priority: "p1"},
	{ID: model.SkillErrorHandling, Name: "error-handling", Category: "quality", Priority: "p1"},
	{ID: model.SkillGitRelease, Name: "git-release", Category: catWorkflow, Priority: "p1"},
	{ID: model.SkillLoggingPatterns, Name: "logging-patterns", Category: "quality", Priority: "p1"},
	{ID: model.SkillPerformance, Name: "performance", Category: "quality", Priority: "p1"},
	{ID: model.SkillPRDescription, Name: "pr-description", Category: catWorkflow, Priority: "p1"},
	{ID: model.SkillRefactoringPR, Name: "refactoring-pr", Category: "quality", Priority: "p1"},
	{ID: model.SkillSecurityAudit, Name: "security-audit", Category: "security", Priority: "p1"},
	{ID: model.SkillTestWriter, Name: "test-writer", Category: "testing", Priority: "p1"},
	// ── Dxrk-specific ────────────────────────────────────────────
	{ID: model.SkillDxrkAPIContent, Name: "dxrk-api-content", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkBatch, Name: "dxrk-batch", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkClaudeAPI, Name: "dxrk-claude-api", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkClaudeChrome, Name: "dxrk-claude-chrome", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkDebug, Name: "dxrk-debug", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkDiscordAgent, Name: "dxrk-discord-agent", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkDream, Name: "dxrk-dream", Category: "dxrk", Priority: "p2"},
	{ID: model.SkillDxrkDuplicateDetect, Name: "dxrk-duplicate-detection", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkGHSA, Name: "dxrk-ghsa-maintainer", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkGitcrawl, Name: "dxrk-gitcrawl", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkKeybindings, Name: "dxrk-keybindings", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkLoop, Name: "dxrk-loop", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkLoremIpsum, Name: "dxrk-lorem-ipsum", Category: "dxrk", Priority: "p2"},
	{ID: model.SkillDxrkParallelsE2E, Name: "dxrk-parallels-e2e", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkParallelsSmoke, Name: "dxrk-parallels-smoke", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkPreRelease, Name: "dxrk-pre-release-testing", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkPRMaintainer, Name: "dxrk-pr-maintainer", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkQATesting, Name: "dxrk-qa-testing", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkRelease, Name: "dxrk-release-maintainer", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkRemember, Name: "dxrk-remember", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkScheduleAgents, Name: "dxrk-schedule-agents", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkSecretScan, Name: "dxrk-secret-scanning", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkSecurityTriage, Name: "dxrk-security-triage", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkSimplify, Name: "dxrk-simplify", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkSkillGenerator, Name: "dxrk-skill-generator", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkSkillify, Name: "dxrk-skillify", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkStuck, Name: "dxrk-stuck", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkTestbox, Name: "dxrk-testbox", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkTesting, Name: "dxrk-testing", Category: "dxrk", Priority: "p0"},
	{ID: model.SkillDxrkTestMemory, Name: "dxrk-test-memory", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkTestOptimize, Name: "dxrk-test-optimize", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkTestPerformance, Name: "dxrk-test-performance", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkUpdateConfig, Name: "dxrk-update-config", Category: "dxrk", Priority: "p1"},
	{ID: model.SkillDxrkVerify, Name: "dxrk-verify", Category: "dxrk", Priority: "p0"},
	// ── Additional Languages ─────────────────────────────────────
	{ID: model.SkillTypeScriptExpert, Name: "typescript-expert", Category: "language", Priority: "p1"},
	{ID: model.SkillNodejsBackend, Name: "nodejs-backend-patterns", Category: "language", Priority: "p1"},
	{ID: model.SkillNodejsBestPractices, Name: "nodejs-best-practices", Category: "language", Priority: "p1"},
	{ID: model.SkillTrpcFullstack, Name: "trpc-fullstack", Category: "language", Priority: "p2"},
	{ID: model.SkillDrizzleORM, Name: "drizzle-orm-expert", Category: "language", Priority: "p2"},
	{ID: model.SkillPrismaExpert, Name: "prisma-expert", Category: "language", Priority: "p2"},
	{ID: model.SkillRubyPro, Name: "ruby-pro", Category: "language", Priority: "p2"},
	{ID: model.SkillPythonTesting, Name: "python-testing-patterns", Category: "testing", Priority: "p1"},
	// ── Additional Web / Frontend ────────────────────────────────
	{ID: model.SkillAngular, Name: "angular", Category: "web", Priority: "p2"},
	{ID: model.SkillAngularBestPractices, Name: "angular-best-practices", Category: "web", Priority: "p2"},
	{ID: model.SkillSvelteKit, Name: "sveltekit", Category: "web", Priority: "p2"},
	{ID: model.SkillTailwindPatterns, Name: "tailwind-patterns", Category: "web", Priority: "p1"},
	{ID: model.SkillReactStateMgmt, Name: "react-state-management", Category: "web", Priority: "p1"},
	// ── Additional DevOps / Cloud ────────────────────────────────
	{ID: model.SkillAWSServerlessEDA, Name: "aws-serverless-eda", Category: "devops", Priority: "p1"},
	{ID: model.SkillAWSPenetration, Name: "aws-penetration-testing", Category: "security", Priority: "p2"},
	{ID: model.SkillAzureCloud, Name: "azure-cloud-architect", Category: "devops", Priority: "p2"},
	{ID: model.SkillDockerDevelopment, Name: "docker-development", Category: "devops", Priority: "p1"},
	{ID: model.SkillDeploymentPipeline, Name: "deployment-pipeline-design", Category: "devops", Priority: "p1"},
	{ID: model.SkillCICDAutomation, Name: "ci-cd-and-automation", Category: "devops", Priority: "p1"},
	{ID: model.SkillKubernetesDeploy, Name: "kubernetes-deployment", Category: "devops", Priority: "p1"},
	{ID: model.SkillKubernetesOperator, Name: "kubernetes-operator", Category: "devops", Priority: "p2"},
	{ID: model.SkillSparkOptimization, Name: "spark-optimization", Category: "data", Priority: "p2"},
	{ID: model.SkillSnowflake, Name: "snowflake-development", Category: "data", Priority: "p2"},
	// ── Additional AI / ML ───────────────────────────────────────
	{ID: model.SkillAIAgentsArchitect, Name: "ai-agents-architect", Category: "ai", Priority: "p0"},
	{ID: model.SkillAgentProtocol, Name: "agent-protocol", Category: "ai", Priority: "p1"},
	{ID: model.SkillAgentMemorySystems, Name: "agent-memory-systems", Category: "ai", Priority: "p1"},
	{ID: model.SkillAISecurity, Name: "ai-security", Category: "ai", Priority: "p1"},
	{ID: model.SkillRAGImplementation, Name: "rag-implementation", Category: "ai", Priority: "p1"},
	{ID: model.SkillPromptEngineer, Name: "prompt-engineer", Category: "ai", Priority: "p1"},
	{ID: model.SkillHuggingFaceTrainer, Name: "hugging-face-model-trainer", Category: "ai", Priority: "p2"},
	{ID: model.SkillEmbeddingStrategies, Name: "embedding-strategies", Category: "ai", Priority: "p2"},
	{ID: model.SkillLangChainArchitect, Name: "langchain-architecture", Category: "ai", Priority: "p2"},
	// ── Additional Data ──────────────────────────────────────────
	{ID: model.SkillDatabaseArchitect, Name: "database-architect", Category: "data", Priority: "p1"},
	{ID: model.SkillDatabaseOptimizer, Name: "database-optimizer", Category: "data", Priority: "p1"},
	{ID: model.SkillSQLDatabase, Name: "sql-database-assistant", Category: "data", Priority: "p1"},
	{ID: model.SkillPostgreSQL, Name: "postgresql", Category: "data", Priority: "p1"},
	{ID: model.SkillPostgresOptimization, Name: "postgresql-optimization", Category: "data", Priority: "p1"},
	{ID: model.SkillSupabase, Name: "supabase", Category: "data", Priority: "p2"},
	// ── Additional Security ──────────────────────────────────────
	{ID: model.SkillSecurityAndHardening, Name: "security-and-hardening", Category: "security", Priority: "p1"},
	{ID: model.SkillSecurityAuditor, Name: "security-auditor", Category: "security", Priority: "p1"},
	{ID: model.SkillSecurityPenTesting, Name: "security-pen-testing", Category: "security", Priority: "p2"},
	{ID: model.SkillSecurityGuidance, Name: "security-guidance", Category: "security", Priority: "p1"},
	{ID: model.SkillSecurityBluebook, Name: "security-bluebook-builder", Category: "security", Priority: "p2"},
	{ID: model.SkillSecurityReqExtract, Name: "security-requirement-extraction", Category: "security", Priority: "p2"},
	{ID: model.SkillSecretsManagement, Name: "secrets-management", Category: "security", Priority: "p1"},
	{ID: model.SkillAPISecurityTesting, Name: "api-security-testing", Category: "security", Priority: "p1"},
	// ── Additional Testing ───────────────────────────────────────
	{ID: model.SkillCypressSkill, Name: "cypress-skill", Category: "testing", Priority: "p2"},
	{ID: model.SkillPlaywrightSkill, Name: "playwright-skill", Category: "testing", Priority: "p1"},
	{ID: model.SkillPlaywrightJava, Name: "playwright-java", Category: "testing", Priority: "p2"},
	{ID: model.SkillUnitTestGenerate, Name: "unit-testing-test-generate", Category: "testing", Priority: "p1"},
	{ID: model.SkillTestingQA, Name: "testing-qa", Category: "testing", Priority: "p1"},
	{ID: model.SkillTDDDrive, Name: "test-driven-development", Category: "testing", Priority: "p1"},
	{ID: model.SkillAPITestSuite, Name: "api-test-suite-builder", Category: "testing", Priority: "p1"},
	{ID: model.SkillAPITestMock, Name: "api-testing-observability-api-mock", Category: "testing", Priority: "p2"},
	// ── Additional Architecture ──────────────────────────────────
	{ID: model.SkillArchitecturePatterns, Name: "architecture-patterns", Category: "architecture", Priority: "p1"},
	{ID: model.SkillBackendArchitect, Name: "backend-architect", Category: "architecture", Priority: "p1"},
	{ID: model.SkillDomainDrivenDesign, Name: "domain-driven-design", Category: "architecture", Priority: "p1"},
	// ── Additional Documentation ─────────────────────────────────
	{ID: model.SkillDocumentation, Name: "documentation", Category: "documentation", Priority: "p1"},
	{ID: model.SkillDocumentationADRs, Name: "documentation-and-adrs", Category: "documentation", Priority: "p1"},
	{ID: model.SkillOpenAPISpec, Name: "openapi-spec-generator", Category: "documentation", Priority: "p1"},
	{ID: model.SkillChangelogGenerator, Name: "changelog-generator", Category: "documentation", Priority: "p2"},
	{ID: model.SkillReadme, Name: "readme", Category: "documentation", Priority: "p2"},
	{ID: model.SkillDocx, Name: "docx", Category: "documents", Priority: "p1"},
	{ID: model.SkillXLSX, Name: "xlsx", Category: "documents", Priority: "p1"},
	{ID: model.SkillPPTX, Name: "pptx", Category: "documents", Priority: "p1"},
	{ID: model.SkillPDF, Name: "pdf", Category: "documents", Priority: "p1"},
	{ID: model.SkillPDFOfficial, Name: "pdf-official", Category: "documents", Priority: "p1"},
	// ── Additional Media ─────────────────────────────────────────
	{ID: model.Skill3DWebExperience, Name: "3d-web-experience", Category: "media", Priority: "p2"},
	{ID: model.SkillThreeJSFundamentals, Name: "threejs-fundamentals", Category: "media", Priority: "p2"},
	{ID: model.SkillThreeJSAnimation, Name: "threejs-animation", Category: "media", Priority: "p2"},
	{ID: model.SkillAIStudioImage, Name: "ai-studio-image", Category: "media", Priority: "p2"},
	{ID: model.SkillAudioTranscriber, Name: "audio-transcriber", Category: "media", Priority: "p2"},
	{ID: model.SkillDemoVideo, Name: "demo-video", Category: "media", Priority: "p2"},
	// ── Additional Business / Writing ────────────────────────────
	{ID: model.SkillAgileProductOwner, Name: "agile-product-owner", Category: "business", Priority: "p2"},
	{ID: model.SkillProductManagerTool, Name: "product-manager-toolkit", Category: "business", Priority: "p2"},
	{ID: model.SkillProductStrategist, Name: "product-strategist", Category: "business", Priority: "p2"},
	{ID: model.SkillScrumMaster, Name: "scrum-master", Category: "business", Priority: "p2"},
	{ID: model.SkillContentHumanizer, Name: "content-humanizer", Category: "writing", Priority: "p1"},
	{ID: model.SkillDevRelContent, Name: "devrel-content", Category: "writing", Priority: "p2"},
	{ID: model.SkillScientificWriting, Name: "scientific-writing", Category: "writing", Priority: "p2"},
	{ID: model.SkillPostmortemWriting, Name: "postmortem-writing", Category: "writing", Priority: "p2"},
	// ── Additional Code Quality ──────────────────────────────────
	{ID: model.SkillBrooksLint, Name: "brooks-lint", Category: "quality", Priority: "p2"},
	{ID: model.SkillCodeReviewer, Name: "code-reviewer", Category: "quality", Priority: "p1"},
	{ID: model.SkillCaveman, Name: "caveman", Category: "quality", Priority: "p1"},
	{ID: model.SkillUnslop, Name: "unslop", Category: "quality", Priority: "p1"},
	{ID: model.SkillUnslopCommit, Name: "unslop-commit", Category: "quality", Priority: "p1"},
	{ID: model.SkillUnslopFile, Name: "unslop-file", Category: "quality", Priority: "p1"},
	{ID: model.SkillUnslopReview, Name: "unslop-review", Category: "quality", Priority: "p1"},
	{ID: model.SkillGrillMe, Name: "grill-me", Category: "quality", Priority: "p1"},
	{ID: model.SkillGrilling, Name: "grilling", Category: "quality", Priority: "p2"},
	{ID: model.SkillGrillWithDocs, Name: "grill-with-docs", Category: "quality", Priority: "p2"},
	{ID: model.SkillHandoff, Name: "handoff", Category: "quality", Priority: "p1"},
	{ID: model.SkillLast30Days, Name: "last30days", Category: "quality", Priority: "p2"},
	{ID: model.SkillCommit, Name: "commit", Category: "quality", Priority: "p1"},
	{ID: model.SkillPRWriter, Name: "pr-writer", Category: "quality", Priority: "p1"},
	{ID: model.SkillSkillOptimizer, Name: "skill-optimizer", Category: "quality", Priority: "p2"},
	{ID: model.SkillSuperpowersLab, Name: "superpowers-lab", Category: "quality", Priority: "p2"},
	{ID: model.SkillUsingSuperpowers, Name: "using-superpowers", Category: "quality", Priority: "p2"},
	// ── Additional Observability / Debugging ─────────────────────
	{ID: model.SkillDatadogAutomation, Name: "datadog-automation", Category: "observability", Priority: "p2"},
	{ID: model.SkillDebuggingCode, Name: "debugging-code", Category: "quality", Priority: "p1"},
	{ID: model.SkillDebuggingStrategies, Name: "debugging-strategies", Category: "quality", Priority: "p1"},
	{ID: model.SkillDebuggingToolkit, Name: "debugging-toolkit", Category: "quality", Priority: "p1"},
	{ID: model.SkillDebuggingRecovery, Name: "debugging-and-error-recovery", Category: "quality", Priority: "p1"},
	{ID: model.SkillPerformanceEngineer, Name: "performance-engineer", Category: "quality", Priority: "p1"},
	{ID: model.SkillPerformanceOptim, Name: "performance-optimization", Category: "quality", Priority: "p1"},
	{ID: model.SkillPerformanceOptimizer, Name: "performance-optimizer", Category: "quality", Priority: "p1"},
	{ID: model.SkillPerformanceProfiler, Name: "performance-profiler", Category: "quality", Priority: "p2"},
	{ID: model.SkillPerformanceProfiling, Name: "performance-profiling", Category: "quality", Priority: "p2"},
	// ── MCP / n8n / Notion / Figma ──────────────────────────────
	{ID: model.SkillMCPBuilder, Name: "mcp-builder", Category: "devops", Priority: "p1"},
	{ID: model.SkillMCPToolDeveloper, Name: "mcp-tool-developer", Category: "devops", Priority: "p1"},
	{ID: model.SkillN8nAgents, Name: "n8n-agents", Category: "devops", Priority: "p2"},
	{ID: model.SkillN8nCodeJS, Name: "n8n-code-javascript", Category: "devops", Priority: "p2"},
	{ID: model.SkillN8nCodePython, Name: "n8n-code-python", Category: "devops", Priority: "p2"},
	{ID: model.SkillN8nErrorHandling, Name: "n8n-error-handling", Category: "devops", Priority: "p2"},
	{ID: model.SkillNotionAutomation, Name: "notion-automation", Category: "devops", Priority: "p2"},
	{ID: model.SkillFigmaAutomation, Name: "figma-automation", Category: "devops", Priority: "p2"},
	{ID: model.SkillGitHubActionsDebug, Name: "github-actions-debugger", Category: "devops", Priority: "p1"},
	{ID: model.SkillGitHubActionsTemplates, Name: "github-actions-templates", Category: "devops", Priority: "p1"},
	{ID: model.SkillGrafanaDashboards, Name: "grafana-dashboards", Category: "observability", Priority: "p2"},
	{ID: model.SkillAgentMemoryMCP, Name: "agent-memory-mcp", Category: "ai", Priority: "p2"},
	{ID: model.SkillHeliumMCP, Name: "helium-mcp", Category: "ai", Priority: "p2"},
	{ID: model.SkillHFMCP, Name: "hf-mcp", Category: "ai", Priority: "p2"},
	{ID: model.SkillMercuryMCP, Name: "mercury-mcp", Category: "ai", Priority: "p2"},
	// ── Environment / DX ─────────────────────────────────────────
	{ID: model.SkillEnvGuide, Name: "environment-setup-guide", Category: "devops", Priority: "p1"},
	{ID: model.SkillEnvSecretsManager, Name: "env-secrets-manager", Category: "security", Priority: "p1"},
	{ID: model.SkillCodexProfiles, Name: "codex-profiles", Category: "quality", Priority: "p2"},
	{ID: model.SkillCodexReview, Name: "codex-review", Category: "quality", Priority: "p2"},
	{ID: model.SkillCodexSubagent, Name: "codex-subagent", Category: "quality", Priority: "p2"},
	{ID: model.SkillCodeReviewOpt, Name: "code-review-optimization", Category: "quality", Priority: "p2"},
}

func MVPSkills() []Skill {
	skills := make([]Skill, len(mvpSkills))
	copy(skills, mvpSkills)
	return skills
}
