// SPDX-License-Identifier: MIT
package dxrkguardian

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/Dxrk777/Dxrk/internal/assets"
	"github.com/Dxrk777/Dxrk/internal/components/filemerge"
	"github.com/Dxrk777/Dxrk/internal/model"
	"github.com/Dxrk777/Dxrk/internal/strconst"
)

// InjectionResult describes all files written by the GGA config injection.
type InjectionResult struct {
	ConfigFile    string
	AgentsFile    string
	ConfigChanged bool
	AgentsChanged bool
}

// FilesWritten returns the list of file paths that were written.
func (r InjectionResult) FilesWritten() []string {
	var files []string
	if r.ConfigFile != "" {
		files = append(files, r.ConfigFile)
	}
	if r.AgentsFile != "" {
		files = append(files, r.AgentsFile)
	}
	return files
}

// PostInstallMessages returns user guidance after GGA setup.
func PostInstallMessages() []string {
	return []string{
		"Run `dxrk-guardian install` in any git project to set up the pre-commit hook",
		"Copy `~/.config/dxrk-guardian/AGENTS.md` to your project root and customize it",
	}
}

// ProviderForAgents auto-detects the GGA provider based on selected agents.
// Priority: claude > opencode > gemini > claude (default).
func ProviderForAgents(agentIDs []model.AgentID) string {
	has := make(map[model.AgentID]bool, len(agentIDs))
	for _, id := range agentIDs {
		has[id] = true
	}

	switch {
	case has[model.AgentClaudeCode]:
		return strconst.StrClaude
	case has[model.AgentOpenCode]:
		return "opencode"
	case has[model.AgentGeminiCLI]:
		return "gemini"
	case has[model.AgentAntigravity]:
		// Antigravity is built on Gemini infrastructure.
		return "gemini"
	case has[model.AgentCodex]:
		return "codex"
	default:
		return strconst.StrClaude
	}
}

// BuildConfig generates the shell-sourced GGA global config content.
func BuildConfig(provider string) []byte {
	var b strings.Builder
	b.WriteString("# Dxrk Guardian Angel Configuration\n")
	b.WriteString("# Generated by dxrk\n")
	b.WriteString("\n")
	b.WriteString("# AI Provider for code review\n")
	b.WriteString("# Options: claude, gemini, codex, opencode, ollama:<model>\n")
	fmt.Fprintf(&b, "PROVIDER=%q\n", provider)
	b.WriteString("\n")
	b.WriteString("# File patterns to review (comma-separated globs)\n")
	b.WriteString("FILE_PATTERNS=\"*.ts,*.tsx,*.js,*.jsx,*.py,*.go\"\n")
	b.WriteString("\n")
	b.WriteString("# Patterns to exclude\n")
	b.WriteString("EXCLUDE_PATTERNS=\"*.test.*,*.spec.*,*.d.ts,dist/*,build/*,node_modules/*\"\n")
	b.WriteString("\n")
	b.WriteString("# Rules file\n")
	b.WriteString("RULES_FILE=\"AGENTS.md\"\n")
	b.WriteString("\n")
	b.WriteString("# Strict mode (fail on ambiguous AI responses)\n")
	b.WriteString("STRICT_MODE=\"true\"\n")
	b.WriteString("\n")
	b.WriteString("# Review timeout in seconds\n")
	b.WriteString("TIMEOUT=\"300\"\n")
	return []byte(b.String())
}

// ConfigPath returns the GGA global config file path.
func ConfigPath(homeDir string) string {
	return filepath.Join(homeDir, ".config", "dxrk-guardian", "config")
}

// AgentsTemplatePath returns the starter AGENTS.md template path.
func AgentsTemplatePath(homeDir string) string {
	return filepath.Join(homeDir, ".config", "dxrk-guardian", "AGENTS.md")
}

// Inject writes the GGA global config and starter AGENTS.md template.
// The provider is auto-detected from the selected agents.
func Inject(homeDir string, agentIDs []model.AgentID) (InjectionResult, error) {
	provider := ProviderForAgents(agentIDs)
	configContent := BuildConfig(provider)
	configPath := ConfigPath(homeDir)

	configResult, err := filemerge.WriteFileAtomic(configPath, configContent, 0o600)
	if err != nil {
		return InjectionResult{}, fmt.Errorf("write dxrk-guardian config: %w", err)
	}

	agentsContent, err := assets.Read("dxrkguardian/AGENTS.md")
	if err != nil {
		return InjectionResult{}, fmt.Errorf("read embedded dxrk-guardian AGENTS.md template: %w", err)
	}

	agentsPath := AgentsTemplatePath(homeDir)
	agentsResult, err := filemerge.WriteFileAtomic(agentsPath, []byte(agentsContent), 0o600)
	if err != nil {
		return InjectionResult{}, fmt.Errorf("write dxrk-guardian AGENTS.md template: %w", err)
	}

	return InjectionResult{
		ConfigFile:    configPath,
		AgentsFile:    agentsPath,
		ConfigChanged: configResult.Changed,
		AgentsChanged: agentsResult.Changed,
	}, nil
}
